[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]
auto-format = true
formatter = { command = "bash", args = ["-c", "ruff check --fix - | ruff format -"] }
# Do not include ruff check
# formatter = { command = "ruff", args = ["format", "-"] }

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.python.analysis]
typeCheckingMode = "basic"


[language-server.ruff]
command = "ruff"
args = ["server"]

