# Se the TPM plugin directory to follow XDG Base Dir Spec
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux/plugins/"

unbind e
bind e source-file ~/.config/tmux/tmux.conf
unbind r
bind r command-prompt "rename-window %%"

# Split panes vertically using the current path
bind % split-window -h -c "#{pane_current_path}"

# Split panes horizontally using the current path
bind '"' split-window -v -c "#{pane_current_path}"

# claude code documentation https://code.claude.com/docs/en/terminal-config
set -g allow-passthrough on

# mouse scroll
set -g mouse on

set -g base-index 1
setw -g mode-keys vi
# set-option -g automatic-rename off
# set-option -g allow-rename off

set-option -g history-limit 10000
set-option -g base-index 1
set-option -g renumber-windows on
# set-option -g status-position top

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Monitor for activity in other windows
setw -g monitor-activity on
set -g visual-activity off  # Don't show tmux's own message

# Enable bell notifications (important for notifications to work)
set -g bell-action any
set -g visual-bell on



set -g @plugin 'tmux-plugins/tpm'
 
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# set -g @plugin 'catppuccin/tmux#v2.1.3' 
# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_right_separator " "
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_window_default_fill "number"
# set -g @catppuccin_window_default_text "#W"
# set -g @catppuccin_window_current_fill "number"
# set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
# set -g @catppuccin_status_modules_right "directory" # date_time"
# set -g @catppuccin_status_modules_left "session"
# set -g @catppuccin_status_left_separator  " "
# set -g @catppuccin_status_right_separator " "
# set -g @catppuccin_status_right_separator_inverse "no"
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_connect_separator "no"
# set -g @catppuccin_directory_text "#{b:pane_current_path}"

run '${XDG_DATA_HOME}/tmux/plugins/tpm/tpm'

